Fix loading of the user email in the "My account" section
Susanfe/sdp-event-management pull request #279
Opened 2018-12-16 15:25 UTC by Fnux

Simple bug fix, the title should be explicit enough.

2018-12-16 16:29 UTC, zyuiop requested changes

2018-12-16 16:29 UTC, zyuiop commented on app/src/main/java/ch/epfl/sweng/eventmanager/ui/user/UserModel.java
> +public class UserModel extends ViewModel {
This class seems useless

2018-12-16 18:49 UTC, Fnux commented on app/src/main/java/ch/epfl/sweng/eventmanager/ui/user/UserModel.java
> +public class UserModel extends ViewModel {
Removed by 06d5f8f.

2018-12-17 10:04 UTC, Luminilion approved these changes

2018-12-17 10:15 UTC, zyuiop approved these changes

2018-12-17 11:01 UTC, merged